export enum UserRole {
  ADMIN = 'ADMIN',
  ADMIN2 = 'ADMIN2',
  COMPANY = 'COMPANY',
  PROVIDER = 'PROVIDER',
  ACCOUNTING = 'ACCOUNTING',
  TREASURY = 'TREASURY',
  USER = 'USER',
  COLABORADOR = 'COLABORADOR',
}
